### ISSUE TITLE
the true positive folder is empty

### ISSUE THREAD

**Issue by Vinoy-UKHSA** [hzi-bifo/Quasimodo#13]
I am trying to use Quasimodo to compare variant calling from different variant callers in a synthetic dataset.  I ran the Quasimodo successfully,(python3 run_benchmark.py vareval) however, the vcf files in "tp" folder did not have any entries except the headers, whereas the vcf files in the “fp” folder has SNP/indel entries (at least some them should be correct calls). Can you advice what is going wrong, and why vcf files in "tp" folder doesn't have any entries. Ideally, we are trying to identify the SNPs/indels which fall into the 4 different category (TP, FP, TN, FN).

**Comment by dawnmy** [comment]
Thank you for reporting the issue. I am looking into this. It seems the VCF file based on genome difference was not generated successfully. I will update the code to solve this in a few days.

**Comment by Vinoy-UKHSA** [comment]
Thanks Zhi-Lou. Can you advise me whether the data in the snp_benchmark table is correct and, it is just the vcf files are not created properly. So, I can carry on with the analysis based on the data in the SNP_benchmark table.

Regards
Vinoy

**Comment by dawnmy** [comment]
The issue should have been solved now. I updated it to v0.4.2. Please update it on your computer by git clone the new version.

**Comment by Vinoy-UKHSA** [comment]
Thanks a lot for fixing the issue very quickly. Is there an option to calculate false negatives and true negatives ?

**Comment by dawnmy** [comment]
So far we do not define TN because we think it is hard to define TN. If you define negatives are all the genome sites without any alternative allele, then you can define TN as those negative sites without SNP identified in the VCF file. We can calculate this if you think it is reasonable. But I think with this definition, the TN will be extremely large for all VCF files, so you won't see difference there.

**Comment by Vinoy-UKHSA** [comment]
Yes, i agree to TN and it will be great to have both the FN and TN calculated.

**Comment by dawnmy** [comment]
I will add TN output option in the next release. But this may take some time.

**Comment by dawnmy** [comment]
v0.4.2 supports more than two references in the mixture for custom variant calling evaluation. As to TN, I still think defining TN (genome length - TP - FP - FN) is not relevant and you can hardly see large difference between variant calls because TP + FP + FN are usually small compared with the genome length. So TNs will be all close to the genome length. If you want, you can easily calculate TN with genome length - TP - FP - FN. I would rather use precision, recall and F1-score to evaluate the performance of variant calls.
